# -*- coding: utf-8 -*-
"""calculadora simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaSWKql0lLf16n8f2mcml1OYM2YLx2Wc
"""

# Calculadora
operação = input('selecione a operação:')
if operação == 'soma':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) + int(b))
if operação == 'subtração':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) - int(b))
if operação == 'multiplicação':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) * int(b))
if operação == 'divisão':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) / int(b))

if operação != 'soma' and operação != 'subtração' and operação != 'multiplicação' and operação != 'divisão':
  print('operação invalida')
  operação = input('selecione uma operação válida:')

  while operação != 'soma' and operação != 'subtração' and operação != 'multiplicação' and operação != 'divisão':
    operação = input('selecione uma operação válida:')
if operação == 'soma':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) + int(b))
if operação == 'subtração':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) - int(b))
if operação == 'multiplicação':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) * int(b))
if operação == 'divisão':
    a = input('primeiro numero:')
    b = input('segundo numero:')
    print(int(a) / int(b))

